# Generated by Django 5.2.7 on 2025-10-14 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_tblusers_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblusers',
            options={'managed': False},
        ),
    ]
