# Generated by Django 5.2.7 on 2025-10-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_tblusers_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblcollege',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblcourse',
            options={'managed': True},
        ),
    ]
