# Generated by Django 5.2.7 on 2025-10-16 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tblcollege_options_alter_tblcourse_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tbldepartment',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblprogram',
            options={'managed': True},
        ),
        migrations.AddField(
            model_name='tblcourse',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblterm'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SectionCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_id', models.CharField(max_length=50)),
                ('program_id', models.CharField(max_length=50)),
                ('section_name', models.CharField(max_length=50)),
                ('number_of_students', models.IntegerField()),
                ('year_level', models.CharField(max_length=20)),
                ('term_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.tblterm')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tblusers')),
            ],
            options={
                'unique_together': {('course_id', 'program_id', 'section_name', 'term_id')},
            },
        ),
    ]
