# Generated by Django 5.2.7 on 2025-10-16 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_tbldepartment_options_alter_tblprogram_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbldepartment',
            name='college',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblcollege'),
        ),
        migrations.AddField(
            model_name='tblprogram',
            name='department',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tbldepartment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tblcourse',
            name='term',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblterm'),
        ),
    ]
