# Generated by Django 5.2.7 on 2025-10-25 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tbldepartment_college_tblprogram_department_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblroles',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tbluserrole',
            options={'managed': True},
        ),
        migrations.AlterField(
            model_name='tblcourse',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.tblterm'),
        ),
        migrations.DeleteModel(
            name='SectionCourse',
        ),
    ]
